/*
 * WARNING: do not edit!
 * Generated by util/mkbuildinf.pl
 *
 * Copyright 2014-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#define PLATFORM "platform: linux-generic64"
#define DATE "built on: Wed May  2 02:54:37 2018 UTC"

/*
 * Generate compiler_flags as an array of individual characters. This is a
 * workaround for the situation where CFLAGS gets too long for a C90 string
 * literal
 */
static const char compiler_flags[] = {
    'c','o','m','p','i','l','e','r',':',' ','a','a','r','c','h','6',
    '4','-','l','i','n','u','x','-','a','n','d','r','o','i','d','-',
    'g','c','c',' ','-','f','P','I','C',' ',' ','-','W','a','l','l',
    ' ','-','O','3',' ','-','f','P','I','C',' ','-','m','a','n','d',
    'r','o','i','d',' ','-','B','/','o','p','t','/','a','n','d','r',
    'o','i','d','-','n','d','k','-','r','1','0','e','/','p','l','a',
    't','f','o','r','m','s','/','a','n','d','r','o','i','d','-','2',
    '1','/','a','r','c','h','-','a','r','m','6','4','/','u','s','r',
    '/','/','l','i','b',' ','-','O','3',' ','-','f','o','m','i','t',
    '-','f','r','a','m','e','-','p','o','i','n','t','e','r',' ','-',
    'W','a','l','l',' ','-','D','O','P','E','N','S','S','L','_','U',
    'S','E','_','N','O','D','E','L','E','T','E',' ','-','D','O','P',
    'E','N','S','S','L','_','P','I','C',' ','-','D','N','D','E','B',
    'U','G',' ','-','D','B','_','E','N','D','I','A','N',' ','-','D',
    'S','H','A','R','E','D','_','E','X','T','E','N','S','I','O','N',
    '=','.','s','o',' ','-','D','O','P','E','N','S','S','L','_','P',
    'I','C',' ','-','D','D','S','O','_','D','L','F','C','N',' ','-',
    'D','H','A','V','E','_','D','L','F','C','N','_','H',' ','-','I',
    '/','o','p','t','/','a','n','d','r','o','i','d','-','n','d','k',
    '-','r','1','0','e','/','p','l','a','t','f','o','r','m','s','/',
    'a','n','d','r','o','i','d','-','2','1','/','a','r','c','h','-',
    'a','r','m','6','4','/','u','s','r','/','i','n','c','l','u','d',
    'e','\0'
};
